../build/X86/gem5.debug \
    --stats-file=simple-concurrent-program-se-stats.txt \
    --debug-flags='GarnetMulticast' \
    ../configs/deprecated/example/se.py \
    --ruby \
    --network=garnet \
    --cpu-type=TimingSimpleCPU \
    --caches \
    --l1d_size=16kB \
    --l1i_size=16kB \
    --l2cache \
    --num-l2cache=16 \
    --num-cpus=16 \
    --num-dirs=16 \
    --topology=Mesh_XY \
    --mesh-rows=4 \
    --cpu-clock=2GHz \
    --mem-size=4GB \
    --cmd=../../simple-concurrent-program/a.out \
    --multicast \
